### ISSUE TITLE
Null Safety problems, not working

### ISSUE THREAD

**Issue by armandojimenez** [bazospa/giphy_get#8]
After upgrading myself to null-safety, and using the latest null-safety version for this package, now it breaks on opening, trying to cast a null to string while parsing Json internally:
`
type 'Null' is not a subtype of type 'String' in type cast
#0      new GiphyPreviewImage.fromJson (package:giphy_get/src/client/models/image.dart:329:24)
#1      new GiphyImages.fromJson (package:giphy_get/src/client/models/images.dart:100:31)
#2      new GiphyGif.fromJson (package:giphy_get/src/client/models/gif.dart:66:27)
#3      new GiphyCollection.fromJson.<anonymous closure> (package:giphy_get/src/client/models/collection.dart:13:60)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
#6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#8      new List.of (dart:core-patch/array_patch.dart:50:28)
#9      ListIterable.toList (dart:_internal/iterable.dart:211:44)
#10     new GiphyCollection.fromJson (package:giphy_get/src/client/models/collection.dart:13:73)
#11     GiphyClient._fetchCollection (package:giphy_get/src/client/client.dart:117:28)
<asynchronous suspension>
#12     _GiphyTabDetailState._loadMore (package:giphy_get/src/views/tab/giphy_tab_detail.dart:232:23)
<asynchronous suspension>
`

**Comment by armandojimenez** [comment]
After updating to new version, now I'm getting the same error in another class, gif.dart:
type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast

**Comment by armandojimenez** [comment]
So... is anyone still working on this package?

**Comment by armandojimenez** [comment]
After the update, still the same error

`[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      new GiphyPreviewImage.fromJson
package:giphy_get/…/models/image.dart:328
#1      new GiphyImages.fromJson
package:giphy_get/…/models/images.dart:100
#2      new GiphyGif.fromJson
package:giphy_get/…/models/gif.dart:66
#3      new GiphyCollection.fromJson.<anonymous closure>
package:giphy_get/…/models/collection.dart:13
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
#6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#8      new List.of (dart:core-patch/array_patch.dart:50:28)
#9      ListIterable.toList (dart:_internal/iterable.dart:211:44)
#10     new GiphyCollection.fromJson
package:giphy_get/…/models/collection.dart:13
#11     GiphyClient._fetchCollection
package:giphy_get/…/client/client.dart:117
<asynchronous suspension>
#12     _GiphyTabDetailState._loadMore
package:giphy_get/…/tab/giphy_tab_detail.dart:232
<asynchronous suspension>
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
`

**Comment by bazookon** [comment]
Fixed in 2.0.1 thanks @TramPamPam

**Comment by armandojimenez** [comment]
Hi, still the same error, now after opening, some gif appears, but on scroll, I get the same error and It does not fetch new gif:

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      new GiphyFullImage.fromJson
package:giphy_get/…/models/image.dart:27
#1      new GiphyImages.fromJson
package:giphy_get/…/models/images.dart:60
#2      new GiphyGif.fromJson
package:giphy_get/…/models/gif.dart:66
#3      new GiphyCollection.fromJson.<anonymous closure>
package:giphy_get/…/models/collection.dart:13
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
#6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#8      new List.of (dart:core-patch/array_patch.dart:50:28)
#9      ListIterable.toList (dart:_internal/iterable.dart:212:44)
#10     new GiphyCollection.fromJson
package:giphy_get/…/models/collection.dart:13
#11     GiphyClient._fetchCollection
package:giphy_get/…/client/client.dart:117
<asynchronous suspension>
#12     _GiphyTabDetailState._loadMore
package:giphy_get/…/tab/giphy_tab_detail.dart:232
<asynchronous suspension>

```

**Comment by bazookon** [comment]
I can't replicate error, do you have more information ore some pull request?

**Comment by armandojimenez** [comment]
Just open the modal using 
```
 final GiphyGif? gif = await GiphyGet.getGif(
              context: context,
              apiKey: ApiKey.giphy,
              lang: context.locale.languageCode,
              searchText: 'Search GIPHY',
              tabColor: Theme.of(context).accentColor,
            );
```
and keep scrolling until it appears and stop loading more gif

**Comment by armandojimenez** [comment]
in image.dart, is receiveing null for mp4 in the json, but the param is not nullable

` factory GiphyFullImage.fromJson(Map&lt;String, dynamic&gt; json) =&gt; GiphyFullImage(      url: json['url'],      width: json['width'],      height: json['height'],      size: json['size'],      mp4: json['mp4'],      mp4Size: json['mp4_size'],      webp: json['webp'],      webpSize: json['webp_size']);`
